#logo: /assets/img/headshot_circle.png
title: Katherine Welbourne
description: Portfolio of Machine Learning and Data Science Projects
theme: jekyll-theme-minimal

# Custom settings for the theme
show_downloads: false       # Disables download links (if supported by the theme)
show_credits: false         # Removes theme credit or author attribution (if supported)
show_github_link: false     # Hides "View the Project on GitHub" (if supported)

# Site details (optional, adjust or remove as necessary)
baseurl: ""                 # Leave empty for the root domain
url: "https://katherine-welbourne.github.io"  # Your site URL
repository: katherine-welbourne/data-science-portfolio  # Repository details (if needed)

# Additional metadata (optional)
author: Katherine Welbourne
email: example@example.com
github_username: katherine-welbourne
linkedin: https://linkedin.com/in/your-profile
