# Basic Site Information
title: Katherine Welbourne
description: Portfolio of Machine Learning and Data Science Projects
url: "https://katherine-welbourne.github.io"  # Your GitHub Pages URL
baseurl: ""  # Leave empty for root domain
repository: katherine-welbourne/data-science-portfolio  # Repository details

# Theme Configuration
remote_theme: mmistakes/minimal-mistakes  # Official Minimal Mistakes theme

# Optional Theme Settings
show_downloads: false       # Disables download links (if supported by the theme)
show_credits: false         # Removes theme credit or author attribution
show_github_link: false     # Hides "View the Project on GitHub" (if supported)

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Author Information
author:
  name: Katherine Welbourne
  email: example@example.com
  github: https://github.com/katherine-welbourne
  linkedin: https://linkedin.com/in/your-profile

# Defaults for Pages and Posts
defaults:
  - scope:
      path: ""  # Applies to all files
    values:
      layout: single
      author: Katherine Welbourne
