title: Katherine Welbourne
#logo: /assets/img/headshot_circle.png
description: Portfolio of Machine Learning and Data Science Projects
show_downloads: false
theme: jekyll-theme-minimal
github:
  is_project_page: false
